# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-04 12:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('location', models.ForeignKey(default='LOCATION', on_delete=django.db.models.deletion.CASCADE, to='photos.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.Topic'),
        ),
    ]
